
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  celery:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:passw0rd@db:5432/ruscord
    command: celery -A backend worker --loglevel=info
    networks:
      - backend

  django:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:passw0rd@db:5432/ruscord
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ruscord
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
  postgres_data: